CREATE SCHEMA IF NOT EXISTS `JagCredit` DEFAULT CHARACTER SET utf8 ;
USE JagCredit;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS agreement;
DROP TABLE IF EXISTS extension;
DROP TABLE IF EXISTS message;
DROP TABLE IF EXISTS tranche;
DROP TABLE IF EXISTS reserved;

CREATE TABLE customer (
  ID int(11) NOT NULL AUTO_INCREMENT UNIQUE,
  FNAME varchar(25) NOT NULL,
  LNAME varchar(25) NOT NULL,
  PERSON_CODE VARCHAR(12) NOT NULL,
  BIRTH_DATE DATE NOT NULL,
  ADDRESS VARCHAR(100) NOT NULL,
  PNONE_MOB INT(8) NOT NULL,
  PHONE_LAND INT(8) NOT NULL,
  WORK_PLACE VARCHAR(50) NOT NULL,
  WORK_POSITION VARCHAR(25)  NOT NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE employee (
 ID int(11) NOT NULL AUTO_INCREMENT UNIQUE,
  FNAME varchar(25) NOT NULL,
  LNAME varchar(25) NOT NULL,
  PERSON_CODE VARCHAR(12) NOT NULL,
  BIRTH_DATE DATE NOT NULL,
  ADDRESS VARCHAR(100) NOT NULL,
  PNONE_MOB INT(8) NOT NULL,
  PHONE_LAND INT(8) NOT NULL,
  WORK_PLACE VARCHAR(50) DEFAULT 'JagCredit, Riga, Proletarskaya ulica 1',
  WORK_POSITION VARCHAR(25)  NOT NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE agreement (
  ID int(11) NOT NULL AUTO_INCREMENT UNIQUE,
  SUM DECIMAL(10,2) NOT NULL,
  INTEREST_RATE DECIMAL(2,2) NOT NULL,
  TERM INT(3) DEFAULT 12,
  TERM_UNIT VARCHAR(5) DEFAULT 'month' CHECK (TERM_UNIT IN('day', 'month')),
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  AGREEMENT_STATUS CHAR(10) DEFAULT 'PROCESSING' CHECK (AGREEMENT_STATUS IN ('CANCELLED', 'APPROVED', 'PROCESSING')),
  IS_EXTENDED BIT DEFAULT 0,
  USER_ID INT(11) ,
  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) REFERENCES 	user(ID)
); 
CREATE TABLE extension (
  ID int(11) NOT NULL AUTO_INCREMENT UNIQUE,
  EXT_TYPE VARCHAR(12) DEFAULT 'prolongation' CHECK (EXT_TYPE ('prolongation', 'penalty')), 
  INTEREST_RATE DECIMAL(2,2),
  COMISSION DECIMAL(10,2) DEFAULT 1,
  AGREEMENT_ID INT(11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (AGREEMENT_ID) REFERENCES agreement(ID)
);
CREATE TABLE tranche (
  ID int(11) NOT NULL AUTO_INCREMENT UNIQUE,
  SUM DECIMAL(11,2) NOT NULL,
  AGREEMENT_ID INT(11) NOT NULL,
  PAYMENT_DATE DATE NOT NULL,
  LASTNAME varchar(25) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (AGREEMENT_ID) REFERENCES agreement(ID)
);
#to be refactored I guess
CREATE TABLE message (
  ID int(11) NOT NULL AUTO_INCREMENT UNIQUE,
  BODY TEXT NOT NULL,
  MES_DATE DATE NOT NULL,
  SENDER_ID INT(11) NOT NULL,
  RECEIVER_ID INT(11) NOT NULL,
  PRIMARY KEY (ID)
);
